apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-recommendation
  labels:
    app: movie-recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-recommendation
  template:
    metadata:
      labels:
        app: movie-recommendation
    spec:
      containers:
        - name: movie-recommendation
          image: <ECR_REPOSITORY_URI>:latest
          ports:
            - containerPort: 5000
