apiVersion: v1
kind: Service
metadata:
  name: movie-recommendation-service
spec:
  type: LoadBalancer
  selector:
    app: movie-recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
